import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#efefef',
    },
    dropdownMenu: {
        height: 50,
        justifyContent: 'center',
        paddingHorizontal: 10,
        backgroundColor: '#eceff1',
    },
    wheel: {
        marginVertical: 20,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        height: 210,
        width: 210,
    },
    placeholderContainer: {
        marginTop: 6.5,
        height: 220, 
        width: 220,
    },
    taskList: {
        flex: 1,
        marginTop: 20,
    },
    taskText: {
        fontSize: 16,
        marginLeft: 10,
        color: '#333333', 
        fontWeight:'bold',
    },
    taskCompletedLine: {
        position: 'absolute',
        height: 2,
        backgroundColor: 'red',
        width: '120%',
        top: '30%',
        marginLeft: -34,
    },
    editText: {
        color: '#64b5f6',
    },
    addButton: {
        alignSelf: 'center',
        marginTop: 5,
        marginBottom: 30,
        width: 65,
        height: 65,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FF7F50', 
        borderRadius: 40, 
        borderWidth: 2,
        borderColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addButtonText: {
        color: '#fff',
        fontSize: 30,
        fontWeight: 'bold',
    },
    dateText: {
        alignSelf: 'center',
        alignItems: 'center',
        fontSize: 16,
        color: '#4A4A4A',
    },
    dateTextContainer: {
        flexDirection: 'row',
        alignItems: 'center', 
        justifyContent: 'center', 
    },
    calendarIcon: {
        width: 25, 
        height: 25, 
        marginRight: 10, 
    },
    centeredView: {
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    centeredViewCalendar: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    confirmButton: {
        backgroundColor: '#0275d8',
        borderRadius: 10,
        paddingVertical: 12,
        paddingHorizontal: 30,
        alignSelf: 'center',
        marginTop: 10,
    },
    confirmButtonText: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 16,
    },
    taskModal: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 20,
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        width: '100%',
        paddingBottom: 30,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#333',
    },
    input: {
        height: 50,
        borderColor: '#ddd',
        borderWidth: 1,
        marginBottom: 15,
        paddingHorizontal: 15,
        borderRadius: 10,
        backgroundColor: '#fafafa',
        fontSize: 16,
    },
    saveButton: {
        backgroundColor: '#6BCB77',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignSelf: 'center', 
    },
    saveButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    cancelButton: {
        backgroundColor: '#FF6B6B',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignSelf: 'center', 
    },
    cancelButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-evenly', 
        marginTop: 5,
    },
    deleteButton: {
        backgroundColor: '#d9534f',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 20,
    },
    deleteButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    wheelContainer: {
        position: 'relative',
        height: 200,
        width: 200,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 100,
        borderWidth: 10,
        borderColor: '#FFA07A',
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    spinButton: {
        position: 'absolute',
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FF7F50',
        borderRadius: 40,
        top: '50%',
        left: '50%',
        marginTop: -40,
        marginLeft: -40,
        borderWidth: 2,
        borderColor: '#FFFFFF',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    spinButtonText: {
        fontSize: 18,
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    logo: {
        flex: 1,
        height: 450,
        width: 255,
        alignSelf: "center",
    },
    rowFront: {
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#eceff1',
        backgroundColor: 'white',
        justifyContent: 'flex-start',
        paddingLeft: 20,
        height: 60,
        flexDirection: 'row',
        shadowOpacity: 0.1,
        shadowRadius: 3,
        shadowColor: 'black',
        shadowOffset: { height: 1, width: 0 },
        elevation: 3,
        borderBottomWidth: 2,
        borderBottomColor: 'white', 
    },
    rowBack: {
        alignItems: 'center',
        backgroundColor: '#DDD',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        height: 60,
    },
    backRightBtn: {
        alignItems: 'center',
        bottom: 0,
        justifyContent: 'center',
        position: 'absolute',
        borderBottomWidth: 2,
        borderColor: '#fff',
        top: 0,
        width: 75,
        height: 60
    },
    backRightBtnLeft: {
        backgroundColor: '#efefef',
        right: 225,
    },
    backRightBtnCenter: {
        backgroundColor: '#efefef',
        right: 75,
    },
    backRightBtnRight: {
        backgroundColor: '#efefef',
        right: 0,
    },
    backRightBtnRightLast: {
        backgroundColor: '#efefef',
        right: 150,
    },
    backTextWhite: {
        color: 'black',
        fontWeight:'bold',
    },
    taskLogo: {
        width: 25,
        height: 25,
    },
    rowFrontContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingLeft: 20,
        paddingRight: 20,
        height: 60,
    },
    pointer: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginTop: -55,
        marginLeft: -15,
        width: 100,
        height: 100,
        color: 'white',
        shadowOpacity: 0.1, 
        shadowRadius: 3,
        shadowColor: 'black',
        shadowOffset: { height: 1, width: 0 },
    },
    calendarModal: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5
    },
    calendar: {
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: 8,
    },
    footer: {
        width: '100%',
        backgroundColor: '#efefef'
    }
});
